[phases.setup]
aptPkgs = ["ffmpeg", "curl"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp && pnpm start"
