name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v7
      - run: node --version && pnpm --version
      - run: pnpm install
      - run: pnpm lint

  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v7
      - run: node --version && pnpm --version
      - run: pnpm install
      - run: pnpm build
